name: foodieapp
description: My Food Delivery app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  bloc: ^8.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  sizer: ^2.0.15
  flutter_svg: ^2.0.0+1
  carousel_slider: ^4.2.1
  firebase_core: ^2.5.0
  firebase_auth: ^4.2.6
  google_sign_in: ^5.4.4
  fluttertoast: ^8.1.3
  flutter_facebook_auth: ^5.0.7
  sign_in_with_apple: ^4.3.0
  crypto: ^3.0.2
  the_apple_sign_in: ^1.1.1
  very_good_cli: ^0.11.0+1
  smooth_page_indicator: ^1.0.1
  firebase_database: ^10.0.14
  http: ^0.13.5
  equatable: ^2.0.5
  dio: ^5.0.1
  shimmer: ^2.0.0
  get: ^4.6.5
  shared_preferences: ^2.0.20
  flutter_switch: ^0.3.2


dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf    
    - family: QuickSand
      fonts:
        - asset : assets/fonts/Quicksand-Regular.ttf
  assets:
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/
    - assets/icons/
    - assets/icons/2.0x/
    - assets/icons/3.0x/
