// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, no_default_cases
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhaiS6yBZvXRYyutVrgBdHmVrLXceu-po',
    appId: '1:300643736688:web:b0b0bac4d633a9204b28b5',
    messagingSenderId: '300643736688',
    projectId: 'food-delivery-app-5ff8c',
    authDomain: 'food-delivery-app-5ff8c.firebaseapp.com',
    databaseURL: 'https://food-delivery-app-5ff8c-default-rtdb.firebaseio.com',
    storageBucket: 'food-delivery-app-5ff8c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiqf2VzRw6x8mrLyuVYIpo6CCIcTOZxtQ',
    appId: '1:300643736688:android:73674de22480fda64b28b5',
    messagingSenderId: '300643736688',
    projectId: 'food-delivery-app-5ff8c',
    databaseURL: 'https://food-delivery-app-5ff8c-default-rtdb.firebaseio.com',
    storageBucket: 'food-delivery-app-5ff8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdI325hcdlDA_VIAtfcA9i1hAQnvAuZsY',
    appId: '1:300643736688:ios:97a458376f9ac2db4b28b5',
    messagingSenderId: '300643736688',
    projectId: 'food-delivery-app-5ff8c',
    databaseURL: 'https://food-delivery-app-5ff8c-default-rtdb.firebaseio.com',
    storageBucket: 'food-delivery-app-5ff8c.appspot.com',
    androidClientId: '300643736688-eu32gu2030rc30flrc0hucmclm614v7t.apps.googleusercontent.com',
    iosClientId: '300643736688-15h83peoglvrm65gvg640be1cqq3o3qp.apps.googleusercontent.com',
    iosBundleId: 'com.ileaf.fooddelivery.foodieapp',
  );
}
